# Generated by Django 5.2.1 on 2025-06-14 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('classified_at', models.DateTimeField(auto_now_add=True)),
                ('detection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='detection.detectionresult')),
            ],
        ),
    ]
