# Generated by Django 5.2.3 on 2025-08-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_classificationresult_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationresult',
            name='is_wrong',
            field=models.BooleanField(default=False),
        ),
    ]
