version: '3.8'

services:
  backend:
    build:
      context: ./sorting_system
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./sorting_system:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-docker-key-for-development-only

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend