# Generated by Django 5.2.1 on 2025-06-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='debug/'),
        ),
    ]
